// UK lang variables

tinyMCE.addToLang('',{
theme_style_select : '-- Стили --',
theme_code_desc : 'Редактировать исходный HTML',
theme_code_title : 'Редактор исходного HTML-кода',
theme_code_wordwrap : 'Перенос слов',
theme_sub_desc : 'Над строкой',
theme_sup_desc : 'Под строкой',
theme_hr_desc : 'Вставить горизонтальную линейку',
theme_removeformat_desc : 'Удалить форматирование',
theme_custom1_desc : 'Ваше описание здесь',
insert_image_border : 'Граница',
insert_image_dimensions : 'Размеры',
insert_image_vspace : 'Верт. отступ',
insert_image_hspace : 'Гориз. отступ',
insert_image_align : 'Выравнивание',
insert_image_align_default : '-- Не задано --',
insert_image_align_baseline : 'Baseline',
insert_image_align_top : 'Top',
insert_image_align_middle : 'Middle',
insert_image_align_bottom : 'Bottom',
insert_image_align_texttop : 'TextTop',
insert_image_align_absmiddle : 'Absolute Middle',
insert_image_align_absbottom : 'Absolute Bottom',
insert_image_align_left : 'Left',
insert_image_align_right : 'Right',
theme_font_size : '-- Размер шрифта --',
theme_fontdefault : '-- Шрифт --',
theme_block : '-- Формат --',
theme_paragraph : 'Параграф',
theme_div : 'Div',
theme_address : 'Адрес',
theme_pre : 'Преформатированный',
theme_h1 : 'Заголовок 1',
theme_h2 : 'Заголовок 2',
theme_h3 : 'Заголовок 3',
theme_h4 : 'Заголовок 4',
theme_h5 : 'Заголовок 5',
theme_h6 : 'Заголовок 6',
theme_colorpicker_title : 'Выберите цвет',
theme_colorpicker_apply : 'Применить',
theme_forecolor_desc : 'Выберите цвет текста',
theme_backcolor_desc : 'Выберите цвет фона',
theme_charmap_title : 'Выберите спец.символ',
theme_charmap_desc : 'Вставить спец.символ',
theme_visualaid_desc : 'Переключить направляющие/невидимые элементы',
insert_anchor_title : 'Вставить/редактировать якорь',
insert_anchor_name : 'Имя якоря',
theme_anchor_desc : 'Вставка/редактирование якоря',
theme_insert_link_titlefield : 'Заголовок',
theme_clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
theme_path : 'Путь',
cut_desc : 'Вырезать',
copy_desc : 'Копировать',
paste_desc : 'Вставить',
link_list : 'Список ссылок',
image_list : 'Список изображений',
browse : 'Обзор',
image_props_desc : 'Свойства изображения',
newdocument_desc : 'Новый документ',
class_name : 'Класс',
newdocument : 'Вы уверены, что хотите очистить содержимое?',
about_title : 'О TinyMCE',
about : 'Описание',
license : 'Лицензия',
plugins : 'Плагины',
plugin : 'Плагин',
author : 'Автор',
version : 'Версия',
loaded_plugins : 'Загруженные плагины',
help : 'Помощь',
not_set : '-- Не выбрано --',
close : 'Close',
toolbar_focus : 'Перекючиться на кнопки инструментов - Alt+Q, Переключиться в редактор - Alt-Z, Переключиться на путь до элемента - Alt-X'
});
